# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
version: 2
  pull_request:
    commit-message:
      prefix: "chore"
      include: "scope"
    pull_request_description: "{{ truncate(pull_request_body, 100) }}"
    
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: actions/checkout

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore:"
    ignore:
    - dependency-name: "ws"
    - dependency-name: "@types/node"
    - dependency-name: "@types/vscode"
    - dependency-name: "@types/ws"
    - dependency-name: "typescript"
      versions: ["5.x"]
